/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversRouteImport } from './routes/univers'
import { Route as FinalRouteImport } from './routes/final'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniversIdRouteImport } from './routes/univers.$id'

const UniversRoute = UniversRouteImport.update({
  id: '/univers',
  path: '/univers',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalRoute = FinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversIdRoute = UniversIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UniversRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/univers': typeof UniversRouteWithChildren
  '/univers/$id': typeof UniversIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/univers': typeof UniversRouteWithChildren
  '/univers/$id': typeof UniversIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/univers': typeof UniversRouteWithChildren
  '/univers/$id': typeof UniversIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/final' | '/univers' | '/univers/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/final' | '/univers' | '/univers/$id'
  id: '__root__' | '/' | '/final' | '/univers' | '/univers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinalRoute: typeof FinalRoute
  UniversRoute: typeof UniversRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/univers': {
      id: '/univers'
      path: '/univers'
      fullPath: '/univers'
      preLoaderRoute: typeof UniversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final': {
      id: '/final'
      path: '/final'
      fullPath: '/final'
      preLoaderRoute: typeof FinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/univers/$id': {
      id: '/univers/$id'
      path: '/$id'
      fullPath: '/univers/$id'
      preLoaderRoute: typeof UniversIdRouteImport
      parentRoute: typeof UniversRoute
    }
  }
}

interface UniversRouteChildren {
  UniversIdRoute: typeof UniversIdRoute
}

const UniversRouteChildren: UniversRouteChildren = {
  UniversIdRoute: UniversIdRoute,
}

const UniversRouteWithChildren =
  UniversRoute._addFileChildren(UniversRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinalRoute: FinalRoute,
  UniversRoute: UniversRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
