/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FinalRouteImport } from './routes/final'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniversIndexRouteImport } from './routes/univers.index'
import { Route as UniversIdRouteImport } from './routes/univers.$id'

const FinalRoute = FinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversIndexRoute = UniversIndexRouteImport.update({
  id: '/univers/',
  path: '/univers/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversIdRoute = UniversIdRouteImport.update({
  id: '/univers/$id',
  path: '/univers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/univers/$id': typeof UniversIdRoute
  '/univers/': typeof UniversIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/univers/$id': typeof UniversIdRoute
  '/univers': typeof UniversIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/univers/$id': typeof UniversIdRoute
  '/univers/': typeof UniversIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/final' | '/univers/$id' | '/univers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/final' | '/univers/$id' | '/univers'
  id: '__root__' | '/' | '/final' | '/univers/$id' | '/univers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinalRoute: typeof FinalRoute
  UniversIdRoute: typeof UniversIdRoute
  UniversIndexRoute: typeof UniversIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/final': {
      id: '/final'
      path: '/final'
      fullPath: '/final'
      preLoaderRoute: typeof FinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/univers/': {
      id: '/univers/'
      path: '/univers'
      fullPath: '/univers/'
      preLoaderRoute: typeof UniversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/univers/$id': {
      id: '/univers/$id'
      path: '/univers/$id'
      fullPath: '/univers/$id'
      preLoaderRoute: typeof UniversIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinalRoute: FinalRoute,
  UniversIdRoute: UniversIdRoute,
  UniversIndexRoute: UniversIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
